version: '3.3'


services:
   appphp2020lowgan:
     depends_on:
       - dblowgan  
     image: lowgan/appphp2020:latest
     ports:
       - "8080:80"
     restart: always
     environment:
       - DB_HOST=
       - DB_USER=
       - DB_PASSWORD=
       - DB_NAME=
   dblowgan:
     image: mysql:5.7
     restart: always
#     ports:
#       - "3306:3306"
   
     environment:
       MYSQL_ROOT_PASSWORD: bob
       MYSQL_DATABASE: univille
       MYSQL_USER: bob
       MYSQL_PASSWORD: bob
     
     volumes:
       - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh